### ISSUE TITLE
Review Code

### ISSUE THREAD

**Issue by peace-bi** [LuuTheNguyen/My-CV#4]
- Util folder only should contains .ts or .js files. These files will handle javascript helper code (Example: encode, decode, formatNumber, formatDate, ...). We will move React Component to other folder.
<img width="1261" alt="Screen Shot 2021-08-28 at 11 08 22 PM" src="https://user-images.githubusercontent.com/14953178/131223941-531bc0eb-924d-48f2-ace3-effdc88f8bc7.png">

- Don't write react code in the index file. Index file should use to export component for shortening import in other component.
<img width="1261" alt="Screen Shot 2021-08-28 at 11 13 57 PM" src="https://user-images.githubusercontent.com/14953178/131224167-1fc10e16-53dc-47e3-90bf-7873abf9eac2.png">

- Shortening import by creating an index file for each component folder.
<img width="1261" alt="Screen Shot 2021-08-28 at 11 19 26 PM" src="https://user-images.githubusercontent.com/14953178/131224254-5876fa58-402d-4ca9-814f-9ba90a328120.png">
Example: In Info folder, create an index.ts file and export component in this index file.
<img width="1261" alt="Screen Shot 2021-08-28 at 11 23 53 PM" src="https://user-images.githubusercontent.com/14953178/131224395-11ba3a49-1f63-41df-aa92-df97ca9592dd.png">

- Duplicate folder, it does confuse. Should refactor structure for easy understanding.
<img width="1261" alt="Screen Shot 2021-08-28 at 11 26 41 PM" src="https://user-images.githubusercontent.com/14953178/131224415-ed1e6111-ade5-4005-afca-d69dcdb748b5.png">

**Comment by tietthinh** [comment]
> Shortening import by creating an index file for each component folder.

Plus, any import of `type` (`interface` or `type`) should use `import type {} from './path'`. This will prevent the TS compiler to `import`  them when compile since it is not necessary in runtime and saving compiling time

**Comment by peace-bi** [comment]
- ViewSideBar should put outside HomePage, because it's React component, we should separate context.
<img width="1178" alt="Screen Shot 2021-09-03 at 12 22 52 PM" src="https://user-images.githubusercontent.com/14953178/131954659-d24e4e9d-af53-46a5-bba8-6c42981d75f5.png">

**Comment by peace-bi** [comment]
I think we should only put name has suffix "Props" when we use it with React. FC... >, all fields inside Props should be the normal name (about, list, data,...)
<img width="1264" alt="Screen Shot 2021-09-03 at 12 28 27 PM" src="https://user-images.githubusercontent.com/14953178/131955329-8f6f9695-d74e-4a66-afc9-f0bf8c68e3ce.png">

**Comment by peace-bi** [comment]
We should `import type` for model from interface folder.
<img width="363" alt="Screen Shot 2021-09-03 at 12 39 53 PM" src="https://user-images.githubusercontent.com/14953178/131955924-5fd16c7b-5f08-4929-8bb5-9d350920d9c8.png">
